import type {
  Agent,
  CostRecord,
  DecisionLedgerEntry,
  EvaluationResult,
  ModelRecord,
  ToolRecord,
  Workflow,
} from "./types";

export const PRINCIPLES = [
  "Not every problem needs an agent.",
  "Not every agent needs a large model.",
  "Not every AI task needs an LLM.",
  "Statistical models remain intelligence.",
  "Deterministic software is sometimes the best AI system.",
  "Intelligence should be allocated, not maximized.",
  "Escalate only when necessary.",
  "Every important intelligence decision should be explainable.",
  "Quality, cost, latency and risk must be considered together.",
  "Human judgment remains part of the system.",
];

export const ESCALATION_LADDER = [
  {
    level: 0,
    name: "Deterministic Computation",
    description:
      "Rules, formulas, SQL and procedural code. Exact, auditable, effectively free. Chosen whenever the problem is fully specified.",
  },
  {
    level: 1,
    name: "Statistical / ML Intelligence",
    description:
      "Regression, time-series, gradient boosting, anomaly detection. Chosen when historical signal is strong and semantics are shallow.",
  },
  {
    level: 2,
    name: "Small / Local Model",
    description:
      "Compact local models for classification, extraction and short-form language work at negligible cost and low latency.",
  },
  {
    level: 3,
    name: "Specialist Agent",
    description:
      "A single tool-using agent with a narrow mandate — research, analysis, drafting — under explicit budget control.",
  },
  {
    level: 4,
    name: "Advanced Reasoning Model",
    description:
      "Long-horizon reasoning for genuinely ambiguous, high-impact problems where cheaper strategies plateau.",
  },
  {
    level: 5,
    name: "Multi-Agent Deliberation",
    description:
      "Planner, researcher, critic and synthesizer working in parallel with cross-validation. Expensive; reserved for strategic work.",
  },
  {
    level: 6,
    name: "Human Decision",
    description:
      "Irreversible, regulated or ethically loaded decisions are routed to a person with the full evidence package attached.",
  },
];

export const COMPRESSION_STAGES = [
  { stage: "Raw input", value: "50,000 documents", reduction: 0 },
  { stage: "Filter", value: "18,400 documents", reduction: 63 },
  { stage: "Deduplicate", value: "9,120 documents", reduction: 82 },
  { stage: "Structure", value: "9,120 records", reduction: 82 },
  { stage: "Sample", value: "4,000 records", reduction: 92 },
  { stage: "Cluster", value: "84 representative passages", reduction: 97 },
  { stage: "Retrieve", value: "1,240 relevant passages", reduction: 95 },
  { stage: "Compress", value: "18 evidence groups", reduction: 99 },
  { stage: "Reason", value: "18 high-value evidence groups", reduction: 93 },
];

export const AGENTS: Agent[] = [
  {
    id: "research-agent",
    name: "Research Agent",
    agentClass: "llm",
    typeLabel: "LLM Agent",
    capability: "Web & Corpus Research",
    model: "Configurable",
    tools: ["Search", "Browser"],
    llmRequired: true,
    reliability: 91,
    status: "available",
  },
  {
    id: "data-analyst",
    name: "Data Analyst",
    agentClass: "hybrid",
    typeLabel: "Hybrid",
    capability: "Data Analysis",
    model: "Optional",
    tools: ["Python", "SQL"],
    llmRequired: false,
    reliability: 96,
    status: "available",
  },
  {
    id: "forecasting-engine",
    name: "Forecasting Engine",
    agentClass: "ml",
    typeLabel: "Statistical / ML",
    capability: "Demand Forecasting",
    model: "XGBoost",
    tools: ["Python"],
    llmRequired: false,
    reliability: 94,
    status: "available",
  },
  {
    id: "optimization-engine",
    name: "Optimization Engine",
    agentClass: "deterministic",
    typeLabel: "Algorithmic",
    capability: "Route Optimization",
    model: "OR-Tools",
    tools: ["Calculator"],
    llmRequired: false,
    reliability: 99,
    status: "available",
  },
  {
    id: "anomaly-sentinel",
    name: "Anomaly Sentinel",
    agentClass: "statistical",
    typeLabel: "Statistical",
    capability: "Deviation Detection",
    model: "Seasonal ESD",
    tools: ["Database"],
    llmRequired: false,
    reliability: 93,
    status: "available",
  },
  {
    id: "strategy-agent",
    name: "Strategy Agent",
    agentClass: "llm",
    typeLabel: "LLM Agent",
    capability: "Strategic Planning",
    model: "Advanced Reasoning",
    tools: ["Search", "Files"],
    llmRequired: true,
    reliability: 88,
    status: "available",
  },
  {
    id: "critic-agent",
    name: "Critic Agent",
    agentClass: "llm",
    typeLabel: "LLM Agent",
    capability: "Adversarial Review",
    model: "Advanced Reasoning",
    tools: [],
    llmRequired: true,
    reliability: 86,
    status: "available",
  },
  {
    id: "classifier-unit",
    name: "Classifier Unit",
    agentClass: "ml",
    typeLabel: "ML",
    capability: "Text Classification",
    model: "Fine-tuned Encoder",
    tools: [],
    llmRequired: false,
    reliability: 92,
    status: "available",
  },
  {
    id: "retrieval-unit",
    name: "Retrieval Unit",
    agentClass: "deterministic",
    typeLabel: "Deterministic",
    capability: "Evidence Retrieval",
    model: "BM25 + Embedding",
    tools: ["Database", "Files"],
    llmRequired: false,
    reliability: 97,
    status: "available",
  },
  {
    id: "synthesizer",
    name: "Synthesizer",
    agentClass: "llm",
    typeLabel: "LLM Agent",
    capability: "Evidence Synthesis",
    model: "Configurable",
    tools: [],
    llmRequired: true,
    reliability: 90,
    status: "degraded",
  },
  {
    id: "sustainability-analyst",
    name: "Sustainability Analyst",
    agentClass: "hybrid",
    typeLabel: "Hybrid",
    capability: "Emissions Accounting",
    model: "Optional",
    tools: ["Python", "Document Parser"],
    llmRequired: false,
    reliability: 89,
    status: "available",
  },
  {
    id: "human-reviewer",
    name: "Human Reviewer",
    agentClass: "human",
    typeLabel: "Human",
    capability: "Final Judgment",
    model: "—",
    tools: [],
    llmRequired: false,
    reliability: 100,
    status: "available",
  },
];

export const MODELS: ModelRecord[] = [
  {
    id: "local-small",
    name: "Local Small Model",
    capability: "Extraction, short answers",
    costProfile: "Negligible",
    latencyProfile: "80–200ms",
    contextCapacity: "8K",
    quality: 74,
    availability: 99.9,
    placement: "local",
    status: "available",
  },
  {
    id: "advanced-reasoning",
    name: "Advanced Reasoning Model",
    capability: "Long-horizon reasoning",
    costProfile: "High",
    latencyProfile: "3–12s",
    contextCapacity: "200K",
    quality: 94,
    availability: 99.2,
    placement: "cloud",
    status: "available",
  },
  {
    id: "vision",
    name: "Vision Model",
    capability: "Image understanding",
    costProfile: "Medium",
    latencyProfile: "1–4s",
    contextCapacity: "32K + images",
    quality: 87,
    availability: 98.4,
    placement: "cloud",
    status: "available",
  },
  {
    id: "embedding",
    name: "Embedding Model",
    capability: "Semantic indexing",
    costProfile: "Very low",
    latencyProfile: "20–60ms",
    contextCapacity: "8K",
    quality: 90,
    availability: 99.9,
    placement: "local",
    status: "available",
  },
  {
    id: "classifier",
    name: "Classifier",
    capability: "Intent & topic labelling",
    costProfile: "Negligible",
    latencyProfile: "10–40ms",
    contextCapacity: "4K",
    quality: 92,
    availability: 99.9,
    placement: "local",
    status: "available",
  },
  {
    id: "forecasting",
    name: "Forecasting Model",
    capability: "Time-series projection",
    costProfile: "Compute only",
    latencyProfile: "100–400ms",
    contextCapacity: "n/a",
    quality: 91,
    availability: 99.7,
    placement: "local",
    status: "available",
  },
  {
    id: "anomaly",
    name: "Anomaly Detection Model",
    capability: "Outlier & drift detection",
    costProfile: "Compute only",
    latencyProfile: "60–150ms",
    contextCapacity: "n/a",
    quality: 88,
    availability: 99.5,
    placement: "local",
    status: "degraded",
  },
  {
    id: "reranker",
    name: "Reranker",
    capability: "Evidence ordering",
    costProfile: "Low",
    latencyProfile: "40–120ms",
    contextCapacity: "16K",
    quality: 85,
    availability: 99.4,
    placement: "local",
    status: "available",
  },
];

export const TOOLS: ToolRecord[] = [
  { id: "sql", name: "SQL", type: "Data", permission: "read", status: "available", avgLatencyMs: 42, successRate: 99.4 },
  { id: "python", name: "Python", type: "Compute", permission: "execute", status: "available", avgLatencyMs: 310, successRate: 97.8 },
  { id: "search", name: "Search", type: "External", permission: "read", status: "available", avgLatencyMs: 780, successRate: 95.1 },
  { id: "files", name: "Files", type: "Storage", permission: "read", status: "available", avgLatencyMs: 26, successRate: 99.8 },
  { id: "calculator", name: "Calculator", type: "Deterministic", permission: "execute", status: "available", avgLatencyMs: 3, successRate: 100 },
  { id: "database", name: "Database", type: "Data", permission: "write", status: "available", avgLatencyMs: 58, successRate: 99.1 },
  { id: "rest", name: "REST API", type: "External", permission: "restricted", status: "degraded", avgLatencyMs: 420, successRate: 93.6 },
  { id: "mcp", name: "MCP Server", type: "Fabric", permission: "restricted", status: "available", avgLatencyMs: 150, successRate: 98.2 },
  { id: "browser", name: "Browser", type: "External", permission: "read", status: "available", avgLatencyMs: 1900, successRate: 91.4 },
  { id: "doc-parser", name: "Document Parser", type: "Ingestion", permission: "read", status: "available", avgLatencyMs: 640, successRate: 96.7 },
];

export const LEDGER: DecisionLedgerEntry[] = [
  {
    id: "dl-1041",
    task: "Demand Forecasting",
    profile: "Structured numerical data",
    candidates: [
      { label: "XGBoost", suitability: 92 },
      { label: "ARIMA", suitability: 77 },
      { label: "LLM", suitability: 41 },
      { label: "Multi-Agent", suitability: 36 },
    ],
    selected: "XGBoost",
    reason: [
      "Strong historical signal",
      "Structured data",
      "Low semantic complexity",
      "Lower cost",
      "Acceptable latency",
    ],
    expectedQuality: 89,
    actualQuality: 91,
    latencyMs: 240,
    cost: 0,
    tokens: 0,
    llmCalls: 0,
    fallback: "ARIMA",
    confidence: 93,
    timestamp: "2026-08-14T08:12:00Z",
  },
  {
    id: "dl-1042",
    task: "Quarterly Sales Decline Investigation",
    profile: "Mixed structured + narrative",
    candidates: [
      { label: "Statistical + ML", suitability: 88 },
      { label: "Specialist Agent", suitability: 71 },
      { label: "Multi-Agent", suitability: 54 },
      { label: "Deterministic", suitability: 33 },
    ],
    selected: "Statistical + ML, then Research Agent",
    reason: [
      "Primary computation is numerical decomposition",
      "Narrative context required only for interpretation",
      "Single agent sufficient for evidence gathering",
    ],
    expectedQuality: 86,
    actualQuality: 88,
    latencyMs: 6400,
    cost: 0.21,
    tokens: 12400,
    llmCalls: 3,
    fallback: "Multi-Agent Deliberation",
    confidence: 87,
    timestamp: "2026-08-14T07:41:00Z",
  },
  {
    id: "dl-1043",
    task: "10,000 Customer Complaints Analysis",
    profile: "High-volume unstructured text",
    candidates: [
      { label: "Cluster + Classify + Targeted LLM", suitability: 90 },
      { label: "Full LLM Pass", suitability: 48 },
      { label: "Statistical Only", suitability: 52 },
      { label: "Multi-Agent", suitability: 44 },
    ],
    selected: "Sampling + Clustering + Targeted LLM",
    reason: [
      "Volume makes a full LLM pass economically irrational",
      "Cluster structure captures 93% of variance",
      "LLM reserved for cluster interpretation only",
    ],
    expectedQuality: 85,
    actualQuality: 84,
    latencyMs: 21800,
    cost: 0.63,
    tokens: 41200,
    llmCalls: 18,
    fallback: "Expanded sampling",
    confidence: 82,
    timestamp: "2026-08-13T16:20:00Z",
  },
  {
    id: "dl-1044",
    task: "Delivery Route Optimization — 50 vehicles",
    profile: "Constrained combinatorial problem",
    candidates: [
      { label: "OR-Tools Solver", suitability: 97 },
      { label: "Heuristic", suitability: 68 },
      { label: "LLM", suitability: 12 },
      { label: "Multi-Agent", suitability: 9 },
    ],
    selected: "OR-Tools Solver",
    reason: [
      "Fully specified objective and constraints",
      "Exact solver outperforms any language model",
      "Zero token expenditure",
    ],
    expectedQuality: 96,
    actualQuality: 97,
    latencyMs: 3100,
    cost: 0,
    tokens: 0,
    llmCalls: 0,
    fallback: "Greedy heuristic",
    confidence: 98,
    timestamp: "2026-08-13T11:05:00Z",
  },
  {
    id: "dl-1045",
    task: "Internal Policy Question",
    profile: "Short retrieval-grounded question",
    candidates: [
      { label: "Retrieval + Small Model", suitability: 94 },
      { label: "Advanced Reasoning Model", suitability: 61 },
      { label: "Specialist Agent", suitability: 40 },
      { label: "Human Review", suitability: 15 },
    ],
    selected: "Retrieval + Small Model",
    reason: ["Answer exists verbatim in policy corpus", "No reasoning depth required"],
    expectedQuality: 88,
    actualQuality: 90,
    latencyMs: 310,
    cost: 0.001,
    tokens: 640,
    llmCalls: 1,
    fallback: "Advanced Reasoning Model",
    confidence: 95,
    timestamp: "2026-08-13T09:52:00Z",
  },
  {
    id: "dl-1046",
    task: "Manufacturing Transformation Plan",
    profile: "Open-ended strategic problem",
    candidates: [
      { label: "Multi-Agent + Human Review", suitability: 89 },
      { label: "Specialist Agent", suitability: 66 },
      { label: "Statistical", suitability: 24 },
      { label: "Deterministic", suitability: 8 },
    ],
    selected: "Multi-Agent Deliberation → Human Review",
    reason: [
      "High business impact and irreversibility",
      "Deep ambiguity with no historical analogue",
      "Adversarial critique materially improves quality",
    ],
    expectedQuality: 84,
    actualQuality: 87,
    latencyMs: 48000,
    cost: 1.94,
    tokens: 138000,
    llmCalls: 26,
    fallback: "Escalate to human strategist",
    confidence: 79,
    timestamp: "2026-08-12T18:33:00Z",
  },
];

export const EVALUATIONS: EvaluationResult[] = [
  { dimension: "Task Success", score: 93, delta: 2, note: "Across 412 simulated runs" },
  { dimension: "Routing Accuracy", score: 96, delta: 4, note: "Selected strategy matched post-hoc optimum" },
  { dimension: "Output Quality", score: 89, delta: -1, note: "Graded against reference answers" },
  { dimension: "Reliability", score: 97, delta: 1, note: "Completed without unhandled failure" },
  { dimension: "Latency", score: 88, delta: 6, note: "P95 within declared budget" },
  { dimension: "Cost Efficiency", score: 94, delta: 9, note: "Cost per resolved task" },
  { dimension: "Token Efficiency", score: 91, delta: 12, note: "Tokens per unit of quality" },
  { dimension: "Tool Success", score: 96, delta: 0, note: "Tool invocations returning valid output" },
  { dimension: "Fallback Rate", score: 7, delta: -3, note: "Lower is better" },
  { dimension: "Human Escalation", score: 4, delta: -1, note: "Lower is better" },
  { dimension: "Confidence Calibration", score: 90, delta: 3, note: "Predicted vs realised accuracy" },
];

export const COST_MIX: CostRecord[] = [
  { label: "Deterministic / Statistical", executions: 42, llmCalls: 0, tokens: 0, cost: 0 },
  { label: "Machine Learning", executions: 21, llmCalls: 0, tokens: 0, cost: 0 },
  { label: "Small / Local Model", executions: 24, llmCalls: 24, tokens: 18400, cost: 0.04 },
  { label: "Specialist Agent", executions: 10, llmCalls: 10, tokens: 96000, cost: 2.1 },
  { label: "Multi-Agent Workflow", executions: 3, llmCalls: 3, tokens: 214000, cost: 5.4 },
];

export const PORTFOLIO = [
  {
    name: "Hertz Radio",
    domain: "Creative & Audience Intelligence",
    intelligence: ["Listener segmentation", "Content scheduling", "Trend detection"],
    agents: ["Classifier Unit", "Research Agent"],
    models: ["Embedding Model", "Forecasting Model"],
    tools: ["SQL", "Search"],
    workflow: "Profiler → Clustering → Small Model → Programming Recommendation",
  },
  {
    name: "AlgoVista",
    domain: "Algorithmic Intelligence",
    intelligence: ["Strategy backtesting", "Regime detection", "Risk bounds"],
    agents: ["Optimization Engine", "Anomaly Sentinel"],
    models: ["Forecasting Model", "Anomaly Detection Model"],
    tools: ["Python", "Database"],
    workflow: "Profiler → Deterministic Backtest → Statistical Validation → Evaluation",
  },
  {
    name: "QiDS",
    domain: "Quality & Inspection Intelligence",
    intelligence: ["Defect classification", "Root-cause analysis", "Sampling design"],
    agents: ["Classifier Unit", "Data Analyst"],
    models: ["Vision Model", "Classifier"],
    tools: ["Python", "Document Parser"],
    workflow: "Profiler → Vision Classification → Statistical RCA → Human Review",
  },
  {
    name: "Datum",
    domain: "Business Intelligence",
    intelligence: ["Metric decomposition", "Narrative reporting", "Anomaly alerts"],
    agents: ["Data Analyst", "Synthesizer"],
    models: ["Local Small Model", "Anomaly Detection Model"],
    tools: ["SQL", "Calculator"],
    workflow: "Profiler → SQL Decomposition → Small Model Narrative → Evaluation",
  },
  {
    name: "Humming",
    domain: "Human Intelligence",
    intelligence: ["Skill inference", "Team composition", "Engagement signals"],
    agents: ["Classifier Unit", "Human Reviewer"],
    models: ["Embedding Model", "Classifier"],
    tools: ["Files", "Database"],
    workflow: "Profiler → Embedding Match → Statistical Fit → Human Decision",
  },
  {
    name: "Mangrove",
    domain: "Sustainability Intelligence",
    intelligence: ["Emissions accounting", "Scenario modelling", "Disclosure drafting"],
    agents: ["Sustainability Analyst", "Research Agent"],
    models: ["Forecasting Model", "Advanced Reasoning Model"],
    tools: ["Document Parser", "Python"],
    workflow: "Profiler → Deterministic Accounting → Scenario ML → Targeted LLM Drafting",
  },
  {
    name: "ARPS",
    domain: "Supply Chain Intelligence",
    intelligence: [
      "Demand forecasting",
      "Inventory optimization",
      "Risk detection",
      "Procurement analysis",
      "Logistics optimization",
    ],
    agents: ["Forecasting Engine", "Optimization Engine", "Anomaly Sentinel"],
    models: ["Forecasting Model", "Anomaly Detection Model"],
    tools: ["SQL", "Python", "REST API"],
    workflow: "Profiler → Forecast → Optimize → Risk Scan → Evaluation",
  },
  {
    name: "Yesdo",
    domain: "Operational Intelligence",
    intelligence: ["Task triage", "SLA prediction", "Workload balancing"],
    agents: ["Classifier Unit", "Optimization Engine"],
    models: ["Classifier", "Forecasting Model"],
    tools: ["Database", "Calculator"],
    workflow: "Profiler → Classification → Deterministic Assignment → Evaluation",
  },
  {
    name: "Treasures of Innocence",
    domain: "Creative Intelligence",
    intelligence: ["Catalogue enrichment", "Narrative generation", "Provenance checks"],
    agents: ["Research Agent", "Synthesizer"],
    models: ["Vision Model", "Local Small Model"],
    tools: ["Files", "Search"],
    workflow: "Profiler → Vision Tagging → Retrieval → Small Model Copy",
  },
  {
    name: "Interview Prep",
    domain: "Education Intelligence",
    intelligence: ["Skill gap analysis", "Adaptive questioning", "Feedback synthesis"],
    agents: ["Classifier Unit", "Strategy Agent"],
    models: ["Local Small Model", "Advanced Reasoning Model"],
    tools: ["Files"],
    workflow: "Profiler → Statistical Gap Analysis → Small Model Drill → LLM Feedback",
  },
  {
    name: "Supergearz",
    domain: "Commerce Intelligence",
    intelligence: ["Pricing elasticity", "Assortment planning", "Fraud screening"],
    agents: ["Data Analyst", "Anomaly Sentinel"],
    models: ["Forecasting Model", "Classifier"],
    tools: ["SQL", "Python"],
    workflow: "Profiler → Elasticity Model → Deterministic Pricing Rules → Evaluation",
  },
  {
    name: "Guardian Holidays",
    domain: "Experience Intelligence",
    intelligence: ["Itinerary optimization", "Demand shaping", "Service recovery"],
    agents: ["Optimization Engine", "Research Agent"],
    models: ["Forecasting Model", "Local Small Model"],
    tools: ["REST API", "Search"],
    workflow: "Profiler → Optimization → Retrieval → Small Model Communication",
  },
];

export const ARCHITECTURE_LAYERS = [
  {
    id: "task",
    name: "Task Understanding",
    detail:
      "Normalises an incoming business mission into an intent, an objective function, constraints and an acceptance definition.",
  },
  {
    id: "profiling",
    name: "Problem Profiling",
    detail:
      "Samples the available data and measures shape, signal, uncertainty and semantic complexity before any model is considered.",
  },
  {
    id: "decision",
    name: "Intelligence Decision",
    detail:
      "Scores every computational paradigm on suitability, quality, cost, latency and risk, then selects the least complex sufficient strategy.",
  },
  {
    id: "paradigms",
    name: "Deterministic · Statistical · AI",
    detail:
      "Three execution families: algorithms and SQL, statistical/ML estimators, and language models or agents. All are first-class.",
  },
  {
    id: "orchestration",
    name: "Orchestration",
    detail:
      "Sequential, parallel and conditional composition with budget enforcement, retries, fallbacks and escalation hooks.",
  },
  {
    id: "tools",
    name: "Tool Fabric",
    detail:
      "Permissioned capability surface — SQL, Python, retrieval, browsers, internal APIs — with latency and success telemetry.",
  },
  {
    id: "mcp",
    name: "MCP",
    detail:
      "Model Context Protocol boundary for connecting external capability servers without embedding integrations in the core.",
  },
  {
    id: "memory",
    name: "Memory + State",
    detail: "Run state, intermediate artefacts, and durable organisational memory used to improve future routing.",
  },
  {
    id: "evaluation",
    name: "Evaluation",
    detail:
      "Grades both the output and the routing decision independently, so a good answer produced expensively still fails review.",
  },
  {
    id: "ledger",
    name: "Decision Ledger",
    detail: "Immutable audit trail of every intelligence decision, its rejected alternatives and its realised outcome.",
  },
  {
    id: "feedback",
    name: "Feedback → Future Routing",
    detail: "Realised quality, cost and latency feed back into suitability priors so the router improves over time.",
  },
];

export const WORKFLOW_TEMPLATES: Workflow[] = [
  {
    id: "wf-research",
    name: "Research & Intelligence",
    description: "Retrieval-first investigation with a single specialist agent and evaluation gate.",
    nodes: [
      { id: "n1", name: "Mission", type: "mission", config: {} },
      { id: "n2", name: "Router", type: "router", config: {} },
      { id: "n3", name: "Retrieval Unit", type: "tool", config: { tool: "Search" } },
      { id: "n4", name: "Research Agent", type: "agent", config: { agent: "Research Agent" } },
      { id: "n5", name: "Evaluator", type: "evaluator", config: {} },
      { id: "n6", name: "Output", type: "output", config: {} },
    ],
    edges: [
      { id: "e1", from: "n1", to: "n2" },
      { id: "e2", from: "n2", to: "n3" },
      { id: "e3", from: "n3", to: "n4" },
      { id: "e4", from: "n4", to: "n5" },
      { id: "e5", from: "n5", to: "n6" },
    ],
  },
  {
    id: "wf-forecast",
    name: "Demand Forecasting",
    description: "Zero-LLM statistical pipeline with deterministic validation.",
    nodes: [
      { id: "n1", name: "Mission", type: "mission", config: {} },
      { id: "n2", name: "Router", type: "router", config: {} },
      { id: "n3", name: "Forecasting Engine", type: "model", config: { model: "XGBoost" } },
      { id: "n4", name: "Backtest", type: "evaluator", config: {} },
      { id: "n5", name: "Output", type: "output", config: {} },
    ],
    edges: [
      { id: "e1", from: "n1", to: "n2" },
      { id: "e2", from: "n2", to: "n3" },
      { id: "e3", from: "n3", to: "n4" },
      { id: "e4", from: "n4", to: "n5" },
    ],
  },
  {
    id: "wf-supply",
    name: "Supply Chain Analysis",
    description: "Forecast, optimise and scan for risk with an algorithmic core.",
    nodes: [
      { id: "n1", name: "Mission", type: "mission", config: {} },
      { id: "n2", name: "Forecasting Engine", type: "model", config: {} },
      { id: "n3", name: "Optimization Engine", type: "agent", config: {} },
      { id: "n4", name: "Risk Condition", type: "condition", config: { threshold: "0.15" } },
      { id: "n5", name: "Output", type: "output", config: {} },
    ],
    edges: [
      { id: "e1", from: "n1", to: "n2" },
      { id: "e2", from: "n2", to: "n3" },
      { id: "e3", from: "n3", to: "n4" },
      { id: "e4", from: "n4", to: "n5" },
    ],
  },
  {
    id: "wf-exec",
    name: "Executive Investigation",
    description: "Multi-agent deliberation with adversarial critique and human approval.",
    nodes: [
      { id: "n1", name: "Mission", type: "mission", config: {} },
      { id: "n2", name: "Data Analyst", type: "agent", config: {} },
      { id: "n3", name: "Research Agent", type: "agent", config: {} },
      { id: "n4", name: "Critic Agent", type: "agent", config: {} },
      { id: "n5", name: "Human Approval", type: "human_approval", config: {} },
      { id: "n6", name: "Output", type: "output", config: {} },
    ],
    edges: [
      { id: "e1", from: "n1", to: "n2" },
      { id: "e2", from: "n1", to: "n3" },
      { id: "e3", from: "n2", to: "n4" },
      { id: "e4", from: "n3", to: "n4" },
      { id: "e5", from: "n4", to: "n5" },
      { id: "e6", from: "n5", to: "n6" },
    ],
  },
  {
    id: "wf-sustain",
    name: "Sustainability Assessment",
    description: "Deterministic accounting first, language models only for disclosure drafting.",
    nodes: [
      { id: "n1", name: "Mission", type: "mission", config: {} },
      { id: "n2", name: "Document Parser", type: "tool", config: {} },
      { id: "n3", name: "Sustainability Analyst", type: "agent", config: {} },
      { id: "n4", name: "Evaluator", type: "evaluator", config: {} },
      { id: "n5", name: "Output", type: "output", config: {} },
    ],
    edges: [
      { id: "e1", from: "n1", to: "n2" },
      { id: "e2", from: "n2", to: "n3" },
      { id: "e3", from: "n3", to: "n4" },
      { id: "e4", from: "n4", to: "n5" },
    ],
  },
  {
    id: "wf-customer",
    name: "Customer Intelligence",
    description: "Compression-led pipeline: sample, cluster, classify, then reason narrowly.",
    nodes: [
      { id: "n1", name: "Mission", type: "mission", config: {} },
      { id: "n2", name: "Sampling", type: "tool", config: {} },
      { id: "n3", name: "Classifier Unit", type: "model", config: {} },
      { id: "n4", name: "Targeted LLM", type: "model", config: {} },
      { id: "n5", name: "Evaluator", type: "evaluator", config: {} },
      { id: "n6", name: "Output", type: "output", config: {} },
    ],
    edges: [
      { id: "e1", from: "n1", to: "n2" },
      { id: "e2", from: "n2", to: "n3" },
      { id: "e3", from: "n3", to: "n4" },
      { id: "e4", from: "n4", to: "n5" },
      { id: "e5", from: "n5", to: "n6" },
    ],
  },
];

export const SYSTEM_HEALTH = [
  { name: "Orchestrator", value: "Operational", ok: true },
  { name: "Router", value: "Operational", ok: true },
  { name: "Agent Registry", value: `${AGENTS.length} Available`, ok: true },
  { name: "Model Registry", value: `${MODELS.length} Available`, ok: true },
  { name: "Tool Fabric", value: `${TOOLS.length} Registered`, ok: true },
  { name: "Evaluation Engine", value: "Operational", ok: true },
];
