import type {
  DataType,
  ExecutionNode,
  IntelligenceStrategy,
  ProblemProfile,
  RoutingDecision,
  StrategyKind,
} from "./types";

export interface MissionBlueprint {
  id: string;
  prompt: string;
  domain: string;
  dataType: DataType;
  profile: Omit<ProblemProfile, "missionId">;
  candidates: IntelligenceStrategy[];
  selected: StrategyKind;
  selectedLabel: string;
  reason: string;
  escalationLevel: number;
  valueOfIntelligence: RoutingDecision["valueOfIntelligence"];
  budget: RoutingDecision["budget"];
  nodes: Omit<ExecutionNode, "status">[];
  llmCalls: number;
}

const s = (
  kind: StrategyKind,
  label: string,
  suitability: number,
  expectedQuality: number,
  estimatedCost: number,
  latencyMs: number,
  risk: IntelligenceStrategy["risk"],
  confidence: number,
): IntelligenceStrategy => ({
  kind,
  label,
  suitability,
  expectedQuality,
  estimatedCost,
  latencyMs,
  risk,
  confidence,
});

const node = (
  id: string,
  name: string,
  type: string,
  column: number,
  parents: string[],
  purpose: string,
  input: string,
  output: string,
  durationMs: number,
  cost: number,
  tokens: number,
  confidence: number,
): Omit<ExecutionNode, "status"> => ({
  id,
  name,
  type,
  column,
  parents,
  purpose,
  input,
  output,
  durationMs,
  cost,
  tokens,
  confidence,
});

export const MISSION_BLUEPRINTS: MissionBlueprint[] = [
  {
    id: "m1",
    prompt: "Forecast next month's product demand.",
    domain: "Supply Chain",
    dataType: "time_series",
    profile: {
      dataType: "time_series",
      signals: [
        { label: "Sample Size", value: "36 months × 214 SKUs" },
        { label: "Missingness", value: "1.4%" },
        { label: "Variance", value: "Moderate" },
        { label: "Outliers", value: "6 detected" },
        { label: "Correlation", value: "Strong seasonal" },
        { label: "Dimensionality", value: "Low" },
        { label: "Temporal Structure", value: "Clear annual cycle" },
      ],
      summary: [
        "Structured numerical problem",
        "High historical signal",
        "Low semantic complexity",
        "Moderate uncertainty",
        "Low reasoning requirement",
      ],
      recommendedStrategy: "machine_learning",
      dimensions: [
        { label: "Problem Complexity", score: 34 },
        { label: "Uncertainty", score: 41 },
        { label: "Business Impact", score: 72 },
        { label: "Latency Requirement", score: 68 },
        { label: "Quality Requirement", score: 80 },
        { label: "Risk", score: 22 },
        { label: "Historical Success", score: 94 },
      ],
    },
    candidates: [
      s("deterministic", "Deterministic", 48, 62, 0, 40, "low", 74),
      s("statistical", "Statistical", 86, 85, 0, 120, "low", 90),
      s("machine_learning", "Machine Learning", 92, 89, 0, 240, "low", 93),
      s("small_model", "Small Model", 38, 61, 0.002, 300, "low", 66),
      s("llm", "LLM", 41, 72, 0.42, 3800, "medium", 58),
      s("specialist_agent", "Specialist Agent", 44, 78, 0.61, 7200, "medium", 61),
      s("multi_agent", "Multi-Agent", 36, 82, 1.8, 18000, "medium", 55),
      s("human_review", "Human Review", 18, 88, 42, 86400000, "low", 70),
    ],
    selected: "machine_learning",
    selectedLabel: "Statistical + ML Analysis",
    reason:
      "Structured numerical data, strong historical signal and low semantic complexity. LLM reasoning is not required for the primary computation.",
    escalationLevel: 1,
    valueOfIntelligence: {
      currentQuality: 89,
      additionalQuality: 2,
      additionalCost: 1.8,
      latencyImpactMs: 17760,
      riskImpact: "medium",
      verdict: "sufficient",
    },
    budget: {
      tokenBudget: 8000,
      usedTokens: 0,
      expectedCost: 0,
      actualCost: 0,
      confidence: 93,
      decision: "stop",
    },
    nodes: [
      node("n1", "Mission", "Intake", 0, [], "Normalise the business request into an objective and constraints.", "Natural language mission", "Objective: minimise forecast error over 30d horizon", 12, 0, 0, 100),
      node("n2", "Problem Profiler", "Profiler", 1, ["n1"], "Measure data shape, signal strength and semantic load.", "214 SKU × 36 month panel", "Structured, high signal, low semantics", 180, 0, 0, 96),
      node("n3", "Intelligence Router", "Router", 2, ["n2"], "Score all paradigms and select the least complex sufficient one.", "Problem profile", "Selected: Statistical + ML", 24, 0, 0, 93),
      node("n4", "Forecasting Engine", "ML", 3, ["n3"], "Gradient-boosted regression with seasonal features.", "Feature matrix", "30-day SKU-level forecast", 240, 0, 0, 91),
      node("n5", "Backtest Evaluation", "Evaluator", 4, ["n4"], "Rolling-origin validation against held-out periods.", "Forecast + actuals", "MAPE 6.8%, within tolerance", 90, 0, 0, 94),
      node("n6", "Result", "Output", 5, ["n5"], "Deliver forecast with confidence bands.", "Validated forecast", "Forecast package delivered", 8, 0, 0, 94),
    ],
    llmCalls: 0,
  },
  {
    id: "m2",
    prompt: "Investigate why quarterly sales declined by 12%.",
    domain: "Business Intelligence",
    dataType: "mixed",
    profile: {
      dataType: "mixed",
      signals: [
        { label: "Sample Size", value: "4 quarters × 11 regions" },
        { label: "Missingness", value: "0.6%" },
        { label: "Variance", value: "High regional" },
        { label: "Outliers", value: "2 regions" },
        { label: "Correlation", value: "Price ↔ volume −0.71" },
        { label: "Dimensionality", value: "Moderate" },
        { label: "Temporal Structure", value: "Quarterly" },
      ],
      summary: [
        "Mixed structured and narrative problem",
        "Decomposable numerically",
        "Interpretation requires external context",
        "Moderate reasoning requirement",
      ],
      recommendedStrategy: "statistical",
      dimensions: [
        { label: "Problem Complexity", score: 62 },
        { label: "Uncertainty", score: 58 },
        { label: "Business Impact", score: 88 },
        { label: "Latency Requirement", score: 40 },
        { label: "Quality Requirement", score: 86 },
        { label: "Risk", score: 44 },
        { label: "Historical Success", score: 81 },
      ],
    },
    candidates: [
      s("deterministic", "Deterministic", 55, 60, 0, 60, "low", 70),
      s("statistical", "Statistical", 92, 89, 0, 120, "low", 91),
      s("machine_learning", "Machine Learning", 78, 85, 0, 400, "low", 84),
      s("small_model", "Small Model", 44, 66, 0.004, 350, "low", 62),
      s("llm", "LLM", 54, 84, 0.42, 3800, "medium", 71),
      s("specialist_agent", "Specialist Agent", 71, 87, 0.61, 8200, "medium", 79),
      s("multi_agent", "Multi-Agent", 47, 91, 1.8, 18000, "medium", 64),
      s("human_review", "Human Review", 30, 92, 60, 86400000, "low", 72),
    ],
    selected: "statistical",
    selectedLabel: "Statistical Decomposition + Research Agent",
    reason:
      "Structured numerical data, strong historical signal and low semantic complexity. Language reasoning is used only to interpret the residual, not to compute it.",
    escalationLevel: 3,
    valueOfIntelligence: {
      currentQuality: 86,
      additionalQuality: 5,
      additionalCost: 1.19,
      latencyImpactMs: 9800,
      riskImpact: "medium",
      verdict: "escalate",
    },
    budget: {
      tokenBudget: 8000,
      usedTokens: 2430,
      expectedCost: 0.24,
      actualCost: 0.21,
      confidence: 91,
      decision: "stop",
    },
    nodes: [
      node("n1", "Mission", "Intake", 0, [], "Frame the decline as a decomposition problem.", "Natural language mission", "Objective: attribute −12% to drivers", 10, 0, 0, 100),
      node("n2", "Problem Profiler", "Profiler", 1, ["n1"], "Assess whether the cause is measurable in the data.", "Sales panel + CRM notes", "Mixed structured/narrative", 210, 0, 0, 94),
      node("n3", "Intelligence Router", "Router", 2, ["n2"], "Split numeric computation from narrative interpretation.", "Problem profile", "Statistical primary, agent secondary", 26, 0, 0, 91),
      node("n4", "Data Analyst", "Hybrid", 3, ["n3"], "SQL decomposition by region, channel and price band.", "Warehouse tables", "Attribution table", 1400, 0, 0, 95),
      node("n5", "Statistical Analysis", "Statistical", 3, ["n3"], "Variance decomposition and significance testing.", "Attribution table", "3 significant drivers", 320, 0, 0, 93),
      node("n6", "Research Agent", "LLM Agent", 4, ["n4", "n5"], "Explain residual variance using external context.", "Unexplained 3.1%", "Competitor promotion identified", 4200, 0.21, 12400, 82),
      node("n7", "Synthesis", "Synthesis", 5, ["n6"], "Assemble a defensible causal narrative.", "Drivers + context", "Executive explanation", 600, 0, 0, 88),
      node("n8", "Evaluation", "Evaluator", 6, ["n7"], "Check attribution sums and citation integrity.", "Narrative", "Passed: 88% quality", 120, 0, 0, 88),
    ],
    llmCalls: 3,
  },
  {
    id: "m3",
    prompt: "Analyze 10,000 customer complaints and identify the main causes.",
    domain: "Customer Intelligence",
    dataType: "text",
    profile: {
      dataType: "text",
      signals: [
        { label: "Document Count", value: "10,000" },
        { label: "Average Length", value: "184 words" },
        { label: "Semantic Diversity", value: "Moderate" },
        { label: "Duplication", value: "31%" },
        { label: "Language", value: "EN 92% / Mixed 8%" },
        { label: "Information Density", value: "Low" },
        { label: "Retrieval Complexity", value: "Low" },
      ],
      summary: [
        "High-volume unstructured text",
        "Heavy duplication and low density",
        "Cluster structure captures most variance",
        "LLM required only for interpretation",
      ],
      recommendedStrategy: "machine_learning",
      dimensions: [
        { label: "Problem Complexity", score: 55 },
        { label: "Uncertainty", score: 48 },
        { label: "Business Impact", score: 74 },
        { label: "Latency Requirement", score: 30 },
        { label: "Quality Requirement", score: 82 },
        { label: "Risk", score: 28 },
        { label: "Historical Success", score: 86 },
      ],
    },
    candidates: [
      s("deterministic", "Deterministic", 26, 40, 0, 200, "low", 60),
      s("statistical", "Statistical", 62, 70, 0, 900, "low", 76),
      s("machine_learning", "Machine Learning", 90, 85, 0.01, 4200, "low", 89),
      s("small_model", "Small Model", 74, 78, 0.02, 2600, "low", 81),
      s("llm", "LLM", 48, 90, 14.2, 320000, "high", 52),
      s("specialist_agent", "Specialist Agent", 58, 86, 2.4, 46000, "medium", 66),
      s("multi_agent", "Multi-Agent", 44, 88, 6.1, 92000, "high", 54),
      s("human_review", "Human Review", 12, 94, 900, 604800000, "low", 68),
    ],
    selected: "machine_learning",
    selectedLabel: "Sampling + Clustering + Targeted LLM",
    reason:
      "A full language-model pass over 10,000 documents is economically irrational. Clustering captures 93% of thematic variance; reasoning is reserved for 18 cluster representatives.",
    escalationLevel: 2,
    valueOfIntelligence: {
      currentQuality: 85,
      additionalQuality: 4,
      additionalCost: 13.6,
      latencyImpactMs: 298000,
      riskImpact: "high",
      verdict: "sufficient",
    },
    budget: {
      tokenBudget: 60000,
      usedTokens: 41200,
      expectedCost: 0.7,
      actualCost: 0.63,
      confidence: 84,
      decision: "stop",
    },
    nodes: [
      node("n1", "Mission", "Intake", 0, [], "Define cause discovery over a complaint corpus.", "10,000 complaints", "Objective: rank root causes", 11, 0, 0, 100),
      node("n2", "Problem Profiler", "Profiler", 1, ["n1"], "Measure duplication, density and diversity.", "Corpus sample", "31% duplication, low density", 900, 0, 0, 92),
      node("n3", "Sampling", "Compression", 2, ["n2"], "Stratified sample preserving rare categories.", "10,000 documents", "4,000 documents", 400, 0, 0, 95),
      node("n4", "Clustering", "ML", 3, ["n3"], "Embedding-space clustering into thematic groups.", "4,000 documents", "84 clusters", 2600, 0.004, 0, 90),
      node("n5", "Classification", "ML", 4, ["n4"], "Assign clusters to a governed taxonomy.", "84 clusters", "18 causes", 800, 0, 0, 89),
      node("n6", "Targeted LLM Reasoning", "LLM", 5, ["n5"], "Interpret only cluster representatives.", "18 evidence groups", "Cause explanations", 12000, 0.63, 41200, 84),
      node("n7", "Synthesis", "Synthesis", 6, ["n6"], "Rank causes by volume and severity.", "Explanations", "Ranked cause report", 700, 0, 0, 86),
      node("n8", "Evaluation", "Evaluator", 7, ["n7"], "Sample-verify labels against human ground truth.", "Report", "84% agreement", 300, 0, 0, 84),
    ],
    llmCalls: 18,
  },
  {
    id: "m4",
    prompt: "Optimize delivery routes for 50 vehicles.",
    domain: "Logistics",
    dataType: "structured",
    profile: {
      dataType: "structured",
      signals: [
        { label: "Sample Size", value: "50 vehicles / 1,840 stops" },
        { label: "Missingness", value: "0%" },
        { label: "Variance", value: "Low" },
        { label: "Outliers", value: "None" },
        { label: "Correlation", value: "n/a" },
        { label: "Dimensionality", value: "High combinatorial" },
        { label: "Temporal Structure", value: "Time windows" },
      ],
      summary: [
        "Fully specified combinatorial problem",
        "Exact objective function available",
        "Zero semantic content",
        "No reasoning requirement",
      ],
      recommendedStrategy: "deterministic",
      dimensions: [
        { label: "Problem Complexity", score: 78 },
        { label: "Uncertainty", score: 12 },
        { label: "Business Impact", score: 84 },
        { label: "Latency Requirement", score: 62 },
        { label: "Quality Requirement", score: 92 },
        { label: "Risk", score: 18 },
        { label: "Historical Success", score: 97 },
      ],
    },
    candidates: [
      s("deterministic", "Deterministic", 97, 96, 0, 3100, "low", 98),
      s("statistical", "Statistical", 40, 58, 0, 200, "low", 62),
      s("machine_learning", "Machine Learning", 52, 71, 0, 1800, "low", 70),
      s("small_model", "Small Model", 14, 32, 0.002, 300, "high", 40),
      s("llm", "LLM", 12, 38, 0.55, 4200, "high", 33),
      s("specialist_agent", "Specialist Agent", 22, 54, 0.9, 9000, "high", 42),
      s("multi_agent", "Multi-Agent", 9, 49, 2.2, 22000, "high", 30),
      s("human_review", "Human Review", 20, 70, 120, 86400000, "medium", 60),
    ],
    selected: "deterministic",
    selectedLabel: "Constraint Solver (OR-Tools class)",
    reason:
      "The objective and constraints are fully specified. An exact solver dominates every probabilistic strategy on quality, cost and auditability. Zero tokens are required.",
    escalationLevel: 0,
    valueOfIntelligence: {
      currentQuality: 96,
      additionalQuality: 0,
      additionalCost: 2.2,
      latencyImpactMs: 18900,
      riskImpact: "high",
      verdict: "sufficient",
    },
    budget: {
      tokenBudget: 8000,
      usedTokens: 0,
      expectedCost: 0,
      actualCost: 0,
      confidence: 98,
      decision: "stop",
    },
    nodes: [
      node("n1", "Mission", "Intake", 0, [], "Translate to a vehicle routing problem.", "Fleet + stop manifest", "VRP with time windows", 9, 0, 0, 100),
      node("n2", "Problem Profiler", "Profiler", 1, ["n1"], "Confirm the problem is fully specified.", "Constraint set", "Deterministic, exact objective", 120, 0, 0, 99),
      node("n3", "Intelligence Router", "Router", 2, ["n2"], "Reject all model-based strategies.", "Problem profile", "Selected: constraint solver", 18, 0, 0, 98),
      node("n4", "Optimization Engine", "Algorithmic", 3, ["n3"], "Branch-and-cut with local search refinement.", "1,840 stops", "50 routes, 11.4% distance saved", 3100, 0, 0, 97),
      node("n5", "Evaluation", "Evaluator", 4, ["n4"], "Verify constraint satisfaction and gap bound.", "Routes", "All constraints satisfied", 60, 0, 0, 98),
      node("n6", "Result", "Output", 5, ["n5"], "Publish routes to dispatch.", "Routes", "Dispatch package", 6, 0, 0, 98),
    ],
    llmCalls: 0,
  },
  {
    id: "m5",
    prompt: "Prepare a strategic transformation plan for a manufacturing company.",
    domain: "Strategy",
    dataType: "documents",
    profile: {
      dataType: "documents",
      signals: [
        { label: "Document Count", value: "412" },
        { label: "Average Length", value: "2,940 words" },
        { label: "Semantic Diversity", value: "Very high" },
        { label: "Duplication", value: "8%" },
        { label: "Language", value: "EN / DE" },
        { label: "Information Density", value: "High" },
        { label: "Retrieval Complexity", value: "High" },
      ],
      summary: [
        "Open-ended strategic problem",
        "No historical analogue",
        "High business impact and irreversibility",
        "High reasoning requirement",
      ],
      recommendedStrategy: "multi_agent",
      dimensions: [
        { label: "Problem Complexity", score: 94 },
        { label: "Uncertainty", score: 88 },
        { label: "Business Impact", score: 97 },
        { label: "Latency Requirement", score: 14 },
        { label: "Quality Requirement", score: 95 },
        { label: "Risk", score: 82 },
        { label: "Historical Success", score: 46 },
      ],
    },
    candidates: [
      s("deterministic", "Deterministic", 8, 20, 0, 100, "high", 30),
      s("statistical", "Statistical", 24, 42, 0, 600, "high", 44),
      s("machine_learning", "Machine Learning", 28, 48, 0.01, 2400, "high", 46),
      s("small_model", "Small Model", 22, 44, 0.01, 1200, "high", 41),
      s("llm", "LLM", 68, 79, 0.9, 14000, "medium", 70),
      s("specialist_agent", "Specialist Agent", 66, 81, 1.2, 26000, "medium", 72),
      s("multi_agent", "Multi-Agent", 89, 90, 1.94, 48000, "medium", 84),
      s("human_review", "Human Review", 92, 95, 0, 172800000, "low", 90),
    ],
    selected: "multi_agent",
    selectedLabel: "Multi-Agent Deliberation → Human Decision",
    reason:
      "High impact, high ambiguity and no historical analogue. Adversarial critique materially improves expected quality, and the final commitment is irreversible — so a human owns the decision.",
    escalationLevel: 5,
    valueOfIntelligence: {
      currentQuality: 79,
      additionalQuality: 11,
      additionalCost: 1.04,
      latencyImpactMs: 34000,
      riskImpact: "low",
      verdict: "escalate",
    },
    budget: {
      tokenBudget: 200000,
      usedTokens: 138000,
      expectedCost: 2.1,
      actualCost: 1.94,
      confidence: 68,
      decision: "escalate",
    },
    nodes: [
      node("n1", "Mission", "Intake", 0, [], "Scope the transformation mandate.", "Board brief + 412 documents", "Objective: 3-year plan", 14, 0, 0, 100),
      node("n2", "Planner", "LLM Agent", 1, ["n1"], "Decompose into workstreams and evidence needs.", "Mandate", "7 workstreams", 6200, 0.31, 21000, 78),
      node("n3", "Research Agent", "LLM Agent", 2, ["n2"], "Gather market and competitor evidence.", "Workstreams", "48 cited findings", 12000, 0.52, 38000, 80),
      node("n4", "Data Analyst", "Hybrid", 2, ["n2"], "Quantify cost base and capacity constraints.", "Financials", "Baseline model", 3400, 0, 0, 93),
      node("n5", "Strategy Agent", "LLM Agent", 3, ["n3", "n4"], "Construct candidate transformation paths.", "Evidence + baseline", "3 strategic options", 9800, 0.58, 41000, 82),
      node("n6", "Critic Agent", "LLM Agent", 4, ["n5"], "Adversarially stress-test each option.", "Options", "12 material objections", 7200, 0.41, 30000, 79),
      node("n7", "Synthesizer", "LLM Agent", 5, ["n6"], "Reconcile critique into a recommended path.", "Options + objections", "Recommended plan", 5400, 0.12, 8000, 84),
      node("n8", "Human Review", "Human", 6, ["n7"], "Executive owner accepts, amends or rejects.", "Plan package", "Awaiting decision", 0, 0, 0, 0),
    ],
    llmCalls: 26,
  },
  {
    id: "m6",
    prompt: "Answer a simple question about a company's internal policy.",
    domain: "Knowledge",
    dataType: "documents",
    profile: {
      dataType: "documents",
      signals: [
        { label: "Document Count", value: "1 policy handbook" },
        { label: "Average Length", value: "84 pages" },
        { label: "Semantic Diversity", value: "Low" },
        { label: "Duplication", value: "2%" },
        { label: "Language", value: "EN" },
        { label: "Information Density", value: "High" },
        { label: "Retrieval Complexity", value: "Very low" },
      ],
      summary: [
        "Retrieval-grounded factual question",
        "Answer exists verbatim in corpus",
        "No reasoning depth required",
        "Low risk",
      ],
      recommendedStrategy: "small_model",
      dimensions: [
        { label: "Problem Complexity", score: 12 },
        { label: "Uncertainty", score: 14 },
        { label: "Business Impact", score: 22 },
        { label: "Latency Requirement", score: 92 },
        { label: "Quality Requirement", score: 70 },
        { label: "Risk", score: 10 },
        { label: "Historical Success", score: 96 },
      ],
    },
    candidates: [
      s("deterministic", "Deterministic", 62, 66, 0, 20, "low", 74),
      s("statistical", "Statistical", 20, 30, 0, 40, "low", 42),
      s("machine_learning", "Machine Learning", 24, 38, 0, 90, "low", 46),
      s("small_model", "Small Model", 94, 88, 0.001, 310, "low", 95),
      s("llm", "LLM", 61, 91, 0.18, 2400, "low", 78),
      s("specialist_agent", "Specialist Agent", 40, 90, 0.4, 6000, "medium", 60),
      s("multi_agent", "Multi-Agent", 10, 91, 1.4, 16000, "medium", 34),
      s("human_review", "Human Review", 15, 96, 12, 3600000, "low", 62),
    ],
    selected: "small_model",
    selectedLabel: "Retrieval + Small Local Model",
    reason:
      "The answer is present verbatim in the policy corpus. Retrieval plus a local model reaches the quality threshold at 0.6% of the cost of a frontier model.",
    escalationLevel: 2,
    valueOfIntelligence: {
      currentQuality: 88,
      additionalQuality: 3,
      additionalCost: 0.179,
      latencyImpactMs: 2090,
      riskImpact: "low",
      verdict: "sufficient",
    },
    budget: {
      tokenBudget: 4000,
      usedTokens: 640,
      expectedCost: 0.001,
      actualCost: 0.001,
      confidence: 95,
      decision: "stop",
    },
    nodes: [
      node("n1", "Mission", "Intake", 0, [], "Interpret a factual policy question.", "User question", "Retrieval query", 6, 0, 0, 100),
      node("n2", "Retrieval", "Deterministic", 1, ["n1"], "Hybrid BM25 + embedding retrieval.", "Policy corpus", "3 passages", 42, 0, 0, 97),
      node("n3", "Small Model", "Local Model", 2, ["n2"], "Grounded extraction and phrasing.", "3 passages", "Answer with citation", 240, 0.001, 640, 92),
      node("n4", "Confidence Check", "Evaluator", 3, ["n3"], "Verify citation support and abstain if weak.", "Answer", "Confidence 95% — accepted", 28, 0, 0, 95),
      node("n5", "Answer", "Output", 4, ["n4"], "Return the grounded answer.", "Verified answer", "Delivered", 4, 0, 0, 95),
    ],
    llmCalls: 1,
  },
];

export function blueprintForPrompt(prompt: string): MissionBlueprint {
  const p = prompt.toLowerCase();
  const match = (...keys: string[]) => keys.some((k) => p.includes(k));
  if (match("forecast", "demand", "predict")) return MISSION_BLUEPRINTS[0]!;
  if (match("route", "vehicle", "optimi", "delivery")) return MISSION_BLUEPRINTS[3]!;
  if (match("complaint", "customer", "reviews", "feedback")) return MISSION_BLUEPRINTS[2]!;
  if (match("strategy", "strategic", "transformation", "plan")) return MISSION_BLUEPRINTS[4]!;
  if (match("policy", "question", "handbook", "simple")) return MISSION_BLUEPRINTS[5]!;
  return MISSION_BLUEPRINTS[1]!;
}
