/**
 * Website generation — LLM generates complete HTML/CSS/JS.
 */

import { callLLM, isLLMConfigured } from "./llm";

export interface SiteGenResult {
  html: string;
  prompt: string;
  latencyMs: number;
  tokens: number;
}

const SITE_SYSTEM_PROMPT = `You are GRAVITY's Website Generator. You create STUNNING, production-ready single-page websites from natural language descriptions.

ABSOLUTE RULES:
1. Return ONLY raw HTML. No markdown fences, no \`\`\`html, no explanations, no comments before/after.
2. Everything must be in a SINGLE file: <!DOCTYPE html> through </html>.
3. ALL CSS must be inline in a <style> tag. ALL JS must be inline in a <script> tag.
4. NO external dependencies — no CDN links, no Google Fonts, no frameworks.

DESIGN SYSTEM (MANDATORY):
- Background: #0a0a0a
- Surface/cards: #141210
- Border: rgba(255,255,255,0.06)
- Primary text: #e8e4dc (warm ivory)
- Secondary text: #8a8478 (muted)
- Accent/gold: #b8960c
- Accent hover: #d4ab14
- Font: system-ui, -apple-system, 'Segoe UI', sans-serif
- Monospace accents: 'SF Mono', 'Cascadia Code', 'Consolas', monospace

TYPOGRAPHY:
- Hero: clamp(40px, 6vw, 72px), font-weight 200, letter-spacing -0.02em
- Section titles: clamp(28px, 4vw, 48px), font-weight 300
- Body: 16px, line-height 1.7, font-weight 300
- Labels/overlines: 10px, letter-spacing 0.17em, uppercase, monospace

LAYOUT:
- Max-width: 1200px centered
- Generous whitespace (padding: 80px 0 for sections)
- CSS Grid and Flexbox for all layouts
- Smooth scroll behavior on html

INTERACTIONS:
- All transitions: 0.3s ease
- Cards: subtle border glow on hover (rgba(184,150,12,0.15))
- Buttons: transparent bg, 1px border, gold text, fill on hover
- Subtle parallax or scroll-triggered animations using IntersectionObserver

QUALITY:
- Semantic HTML5 (header, main, section, article, footer)
- Mobile responsive (media queries or clamp())
- Complete — not a wireframe, not placeholder text
- Real content that matches the user's request
- Professional spacing, alignment, visual hierarchy`;

export async function generateWebsite(
  prompt: string,
  options?: { maxTokens?: number },
): Promise<SiteGenResult> {
  if (!isLLMConfigured()) {
    throw new Error("LLM not configured — cannot generate website");
  }

  const start = Date.now();

  const result = await callLLM({
    tier: "general",
    system: SITE_SYSTEM_PROMPT,
    prompt: `Create a complete, production-ready website for:\n\n${prompt}\n\nReturn ONLY the raw HTML — nothing else.`,
    maxTokens: options?.maxTokens ?? 4500,
    timeoutMs: 35_000,
  });

  const html = cleanHTML(result.text);

  return {
    html,
    prompt,
    latencyMs: Date.now() - start,
    tokens: result.tokens,
  };
}

export async function refineWebsite(
  originalHtml: string,
  feedback: string,
): Promise<SiteGenResult> {
  if (!isLLMConfigured()) {
    throw new Error("LLM not configured — cannot refine website");
  }

  const start = Date.now();

  const result = await callLLM({
    tier: "general",
    system:
      SITE_SYSTEM_PROMPT +
      "\n\nYou are now refining an existing page. You receive the current HTML and modification instructions. " +
      "Return the COMPLETE modified HTML page — not just the changes.",
    prompt: `Current page HTML:\n${originalHtml.slice(0, 5000)}\n\n---\nModification: ${feedback}\n\nReturn the COMPLETE updated HTML page.`,
    maxTokens: 4500,
    timeoutMs: 35_000,
  });

  const html = cleanHTML(result.text);

  return { html, prompt: feedback, latencyMs: Date.now() - start, tokens: result.tokens };
}

/**
 * Clean LLM output: strip markdown fences, ensure valid HTML document.
 */
function cleanHTML(raw: string): string {
  let html = raw
    .replace(/^```(?:html|HTML)?\s*\n?/gm, "")
    .replace(/```\s*$/gm, "")
    .replace(/^Here (?:is|'s) (?:the |a )?(?:complete|full|production-ready|single-page).*?\n/gim, "")
    .trim();

  // Already a full document
  if (html.toLowerCase().includes("<!doctype") || html.toLowerCase().startsWith("<html")) {
    return html;
  }

  // Wrap fragment in full document
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated by GRAVITY</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: #0a0a0a; color: #e8e4dc; font-family: system-ui, sans-serif; }
  </style>
</head>
<body>
${html}
</body>
</html>`;
}
