/**
 * Website generation via LLM — produces a complete HTML/CSS/JS page
 * from a natural language prompt.
 */

import { callLLM, isLLMConfigured } from "./llm";

export interface SiteGenResult {
  html: string;
  prompt: string;
  latencyMs: number;
  tokens: number;
}

/**
 * Generate a complete website HTML from a natural language prompt.
 * Uses Gemini Flash (free tier) for code generation.
 */
export async function generateWebsite(
  prompt: string,
  options?: { maxTokens?: number },
): Promise<SiteGenResult> {
  if (!isLLMConfigured()) {
    throw new Error("LLM not configured — cannot generate website");
  }

  const start = Date.now();

  const system = `You are a world-class frontend developer. You generate COMPLETE, production-ready HTML pages from natural language descriptions.

RULES:
1. Return ONLY the HTML code — no explanations, no markdown fences, no preamble.
2. The HTML must be a single self-contained file with embedded CSS and JS.
3. Use modern CSS (grid, flexbox, variables) — no external dependencies.
4. Make it visually stunning — dark themes, smooth animations, clean typography.
5. Include responsive design (mobile-friendly).
6. If the user asks for a specific type (landing page, dashboard, portfolio, etc.), match industry-standard patterns.
7. Use semantic HTML5 elements.
8. Include smooth scroll behavior, hover effects, and micro-interactions where appropriate.
9. The page must look complete and professional — not a wireframe.

CSS THEME:
- Background: #0a0a0a (dark void)
- Text: #e8e4dc (warm ivory)
- Accent: #b8960c (muted gold)
- Font: system-ui stack
- Border: rgba(255,255,255,0.06)`;

  const result = await callLLM({
    tier: "general",
    system,
    prompt: `Generate a complete, production-ready HTML page for:\n\n${prompt}`,
    maxTokens: options?.maxTokens ?? 4000,
    timeoutMs: 35_000,
  });

  // Clean up the output — remove markdown fences if present
  let html = result.text
    .replace(/```html\n?/gi, "")
    .replace(/```\n?/gi, "")
    .trim();

  // Ensure it's valid HTML
  if (!html.toLowerCase().includes("<!doctype") && !html.toLowerCase().includes("<html")) {
    // Wrap in full HTML document if the LLM returned just a fragment
    html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated by GRAVITY</title>
</head>
<body>
${html}
</body>
</html>`;
  }

  return {
    html,
    prompt,
    latencyMs: Date.now() - start,
    tokens: result.tokens,
  };
}

/**
 * Refine an existing website HTML based on user feedback.
 */
export async function refineWebsite(
  originalHtml: string,
  feedback: string,
): Promise<SiteGenResult> {
  if (!isLLMConfigured()) {
    throw new Error("LLM not configured — cannot refine website");
  }

  const start = Date.now();

  const result = await callLLM({
    tier: "general",
    system:
      "You are a frontend developer. You receive an HTML page and modification instructions. " +
      "Return the COMPLETE modified HTML page — no explanations, no markdown fences. " +
      "Keep the same design language and theme. Apply the requested changes precisely.",
    prompt: `Current HTML:\n\n${originalHtml.slice(0, 6000)}\n\n---\n\nModifications requested:\n${feedback}`,
    maxTokens: 4000,
    timeoutMs: 35_000,
  });

  let html = result.text
    .replace(/```html\n?/gi, "")
    .replace(/```\n?/gi, "")
    .trim();

  if (!html.toLowerCase().includes("<!doctype") && !html.toLowerCase().includes("<html")) {
    html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated by GRAVITY</title>
</head>
<body>
${html}
</body>
</html>`;
  }

  return {
    html,
    prompt: feedback,
    latencyMs: Date.now() - start,
    tokens: result.tokens,
  };
}
